[package]
name = "sample"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
web-sys = "0.3.69"
wasm-bindgen = "0.2.92"
rand = "0.8"
gloo-console = "0.3"

